services:
    we-webserver:
        image: we-webserver
        container_name: we-webserver
        build:
            context: .
            dockerfile: docker/Dockerfile
        env_file:
            - docker/.docker.env
        depends_on:
            - we-sql-server
            - we-mail-server
        links:
            - we-sql-server
            - we-mail-server
        volumes:
            - .:/var/www/html
        ports:
            - "${APP_HOST_PORT}:80"
        networks:
            - we-network
    we-scheduler:
        image: we-scheduler
        container_name: we-scheduler
        build:
            context: .
            dockerfile: docker/SchedulerDockerfile
        depends_on:
            - we-sql-server
            - we-mail-server
            - we-webserver
        links:
            - we-sql-server
            - we-mail-server
            - we-webserver
        volumes:
            - .:/var/www/html
        ports:
            - "9000:8000"
        networks:
            - we-network
    we-sql-server:
        image: we-sql-server
        container_name: we-sql-server
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/SQLDockerfile
        volumes:
            - we-sql-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_HOST_PORT}:${DB_PORT}"
        networks:
            - we-network
    we-mail-server:
        image: axllent/mailpit
        container_name: we-mail-server
        restart: unless-stopped
        volumes:
            - we-mail-data:/data
        ports:
            - "8025:8025"
            - "1025:1025"
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - we-network
volumes:
    we-sql-data:
        driver: "local"
    we-mail-data:
        driver: "local"

networks:
    we-network:
