services:
    we-webserver:
        image: we-webserver
        container_name: we-webserver
        build:
            context: .
            dockerfile: docker/Dockerfile
        env_file:
            - docker/.docker.env
        environment:
            CONTAINER_ROLE: app
            XDEBUG_CONFIG: remote_host=host.docker.internal
        depends_on:
            - we-sql-server
        links:
            - we-sql-server
        volumes:
            - .:/var/www/html
        ports:
            - "${APP_HOST_PORT}:80"
    we-sql-server:
        image: we-sql-server
        container_name: we-sql-server
        build:
            context: .
            dockerfile: docker/SQLDockerfile
        volumes:
            - we-sql-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_HOST_PORT}:${DB_PORT}"
    we-mail-server:
        image: axllent/mailpit
        container_name: we-mail-server
        restart: unless-stopped
        volumes:
            - we-mail-data:/data
        ports:
            - "8025:8025"
            - "1025:1025"
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
    we-sql-data:
        driver: "local"
    we-mail-data:
        driver: "local"
